// <auto-generated />
using System;
using CmdApp.Data_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CmdApp.Migrations
{
    [DbContext(typeof(HealthContext))]
    partial class HealthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CmdApp.Models.Ailment", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("PatientID");

                    b.HasKey("Name");

                    b.HasIndex("PatientID");

                    b.ToTable("Ailments");
                });

            modelBuilder.Entity("CmdApp.Models.Medication", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Doses");

                    b.Property<int?>("PatientID");

                    b.HasKey("Name");

                    b.HasIndex("PatientID");

                    b.ToTable("Medications");
                });

            modelBuilder.Entity("CmdApp.Models.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("PatientID");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("CmdApp.Models.Ailment", b =>
                {
                    b.HasOne("CmdApp.Models.Patient")
                        .WithMany("Ailments")
                        .HasForeignKey("PatientID");
                });

            modelBuilder.Entity("CmdApp.Models.Medication", b =>
                {
                    b.HasOne("CmdApp.Models.Patient")
                        .WithMany("Medications")
                        .HasForeignKey("PatientID");
                });
#pragma warning restore 612, 618
        }
    }
}
